### ISSUE TITLE
Async pg support 

### ISSUE THREAD

**Issue by psevdognom** [ckkz-it/aiohttp-rest-framework#2]
Hello, does it work with asyng instead of aiopg?
I used to work with drf, but now I work with aiohttp with Gino orm. I am looking for a framework for validate, serialize data.

**Comment by ckkz-it** [comment]
Moved to https://github.com/encode/databases library, which uses asyncpg as a default driver (and aiopg can still be used). Please use v0.0.4 for this https://pypi.org/project/aiohttp-rest-framework/
